Somewhat hacky but effective way to implement IDX/IMG LBA Seek.
Xeeynamo/OpenKh pull request #349
Opened 2021-01-03 21:47 UTC by Topaz-Reality

Does what the title says. Seeks out the LBA Offset of the IDX and IMG from the ISO.
This is hacky, but as far as I have seen, it works with everything tested.

Addresses #348.

Tested ISOs:
-> KH2US
-> KH2FM
-> KH2CCZ

Of course, more testing is necessary. But this will do until we have a proper ISO library.

2021-01-03 22:25 UTC, Xeeynamo requested changes
Small tip: use `var` instead of the explicit type when possible

2021-01-03 22:25 UTC, Xeeynamo commented on OpenKh.Command.IdxImg/Program.cs
> +                            byte[] hayRead = reader.ReadBytes(0x0B);
Suggestion here to replace `0x0B` with a constant (eg. `NeedleLength`) and use it when declaring those arrays above (eg. `imgNeedle = new byte[NeedleLength]` so the reason why it is required to read that amount of byte is more explicit.

2021-01-03 22:25 UTC, Xeeynamo commented on OpenKh.Command.IdxImg/Program.cs
> +                    using (BinaryReader reader = new BinaryReader(new MemoryStream(haystack)))
I believe it is not required to read a `0x500` block and using it in the `BinaryReader`. Can you do `new BinaryReader(isoStream)` instead? If you are concerned about performance, you can wrap `isoStream` with a `BufferedStream`.

2021-01-03 22:25 UTC, Xeeynamo commented on OpenKh.Command.IdxImg/Program.cs
> +            bool CompareArrays(byte[] input1, byte[] input2)
No need to create a dedicated function. `input1.SequenceEqual(input2)` will be good enough and it's fast when comparing two arrays of the same length!

2021-01-03 22:25 UTC, Xeeynamo commented on OpenKh.Command.IdxImg/Program.cs
> +                                    IdxIsoBlock = BitConverter.ToInt32(blockCorrect);
I never considered to use `BitConverter.ToInt32`. Thanks for sharing this tip :)

2021-01-03 22:25 UTC, Xeeynamo commented on OpenKh.Command.IdxImg/Program.cs
> +                // Begin being hacky.
No need to specify this is an hack as long as it works ^^

2021-01-03 22:31 UTC, Xeeynamo commented
Another suggestion: if you still plan to use that buffer of `0x500` you can actually get rid of `BinaryReader` and the `ReadBytes` all together. .NET Core 3.1 comes with `Span<T>`, so you can slice a portion of an array with no performance impact. For instance, those two expressions are functionally equivalent, but the second one is more performant:

```csharp
var reader = new BinaryReader(new MemoryStream(buffer));
reader.BaseStream.Position = 5;
var data = reader.ReadBytes(11)
```
with Span<T>:
```csharp
var data = new Span(buffer, 5, 11);
```

2021-01-03 22:52 UTC, Topaz-Reality commented
Changes made.

2021-01-05 17:32 UTC, Xeeynamo approved these changes

2021-01-05 17:32 UTC, merged